### ISSUE TITLE
这是什么动物

### ISSUE THREAD

**Issue by Rain-0x01-39** [Yv-gy/Yv-gy#1]
答：鸽子

**Comment by Yv-gy** [comment]
> 答：鸽子

咕咕咕！
咕咕咕！
**咕咕咕！**

**Comment by Yv-gy** [comment]
咕咕咕！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: SZ2528 ***@***.***>
Sent: Wednesday, March 22, 2023 4:44:45 PM
To: Yv-gy/Yv-gy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Yv-gy/Yv-gy] 这是什么动物 (Issue #1)


答：鸽子

―
